# Generated by Django 4.2.1 on 2023-05-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spend',
            old_name='date_completed',
            new_name='Creation_date',
        ),
    ]
