# Generated by Django 4.2.1 on 2023-05-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0002_rename_date_completed_spend_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spend',
            old_name='Creation_date',
            new_name='creation_date',
        ),
    ]
