# Generated by Django 4.2.1 on 2023-05-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0003_rename_creation_date_spend_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spend',
            old_name='creation_date',
            new_name='Creation_date',
        ),
    ]
