# Generated by Django 4.2.1 on 2023-05-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0005_alter_spend_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='category',
            field=models.CharField(choices=[('Meals', '餐飲費'), ('transportation', '交通'), ('groceries', '購物'), ('entertainment', '娛樂'), ('apparel', '衣服'), ('Pay', '繳費'), ('other', '其他')], max_length=20),
        ),
    ]
