# Generated by Django 4.2.1 on 2023-05-24 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0006_alter_spend_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='Creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
