# Generated by Django 4.2.1 on 2023-05-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0007_alter_spend_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='Creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
