# Generated by Django 4.2.1 on 2023-05-24 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0009_alter_spend_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='Creation',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
