# Generated by Django 4.2.1 on 2023-06-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0011_alter_spend_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='Creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
