# Generated by Django 4.2.1 on 2023-06-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0012_alter_spend_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='Creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
