# Generated by Django 4.2.1 on 2023-06-11 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0013_alter_spend_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='Creation_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
